BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXX
    XXXXXXXX XXXX XX XXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXX
      XX XXXXXXXXXXXXX XXXXX XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
