BBBBBBB BBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBXXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXXXXXX XXXXXXXXXXXX
  XXXX
  BB BBBBBBBB
    BBB BBBBBBB BB BBBBBBBB
      XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    BBBBBB
  BBBBB

  XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXX XXXXXXXXX
        
        
      XXXXXX
      XXXX XXXXXXXXXXXXXXX XXXXXX
        XXXXXXXXXXX XXXXXXXXX
        
        

        XXXXXXXX
        
        
      XXXXXX
    XXXXXX

    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXXX

  XXXX
  XXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
  BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
    XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
  BBBB
    XXXXX XXXXXXX XXXXXXX XXXXXXXX
  BBBBB
XXXXXX
BBBBBBBB
