BBBBBBB BBBBBBBBBBB
BBBB BBBBBB
BBBBB BBBBBXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXX XXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXX
    XXXXXXXXXX XXXX XX XXXXXXXXXXXX
    XX XXXXXXBBB BBBBBBBX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXX
  XXXX XXXXX XXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXX XX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXX XXXXXXXXXX XXXX XXX XXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            
          XXXXXX
  
        XXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
      XXXXXXX

       XX XXXXXXXXXXXXX XXXXXX XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BB BBBBBBBBBBB
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
    
  XXXXXX
BBBBB

BBBBBBBB
