# Generated by Django 5.1.7 on 2025-03-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_phone_profile_phone_number_and_more'),
        ('accounts', '0003_create_missing_profiles'),
    ]

    operations = [
    ]
