BBBB BBBBBB
BBBB BBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXX
XXXXXX
  XXXXX XXXXXXXXXXXXXXXX
  XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  XXXXXXXBBBBB BBBBB gettext(u'Quickdrop') BBBBBBBBXXXXXXXX
  
  XXXX XXXXXXXXX XXX XXX XXX XXX
  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
  
  XXXX XXXXXXXXX XXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXX XXXXXXXXXXX XXXXXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXX XXXX XXXXXXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  XXXX XXXXXX XXX XXX
  XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
  
  XXXXXXX
    XX XXXXXXXXXX XXX XXXXX XX XXXXX XXXXXXXX XX XX XXXXX XX XXXXXX XXXXXXXX XXXXXXXXXXXXX
       XXXX XXXX XXXXX XXXXXXX XX XXX XXXXX XXXXX XXXXXX XX
    XXXXXXXXXXXXXXXXX X
      XXXXXX XXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXX
      XXXXX XXXX
      XXXXXXXXXX XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX X XXXX XXXX XXXXX
    X
    XXXXXX XXXXXXXXXXX XXXXXX X
      XXXXXXXXXXXXXXXXX X
        XXXXXX XXXXX XXXXXXXXXXX
      X
    X
    XX XXXXXXXXX XXXXXX XXXXXXXX XX
    XXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXX XXXXX
      XXXXXXXX XXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
      XXXXXXXXX XXXXXXXXX
      XXXXXXXXXXX XXXXXXX
    X
    XX XXXXX XXXXX XX XXXXXXXX XX
    XXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXX XXXXXXXXX
      XXXX XXXXX
      XXXXX XXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXX XXXXXXXX
      XXXXXX XXXXX
    X
    XX XXXXX XXXXX XXXXXX XX XXX XX
    XXXXXXX X
      XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXX
      XXXXXXXXXXXXXX XXX XXXXX XXXXX
      XXXXXXX XX
      XXXXXXXX XXXXXX XXXXX
      XXXXXXXXX XXXXXX
      XXXX XX
      XXXXXX XXXXX
      XXXXXXXX XXXXX
    X
    XX XXXXX XXXX XX XXXXXXX XXXXXXXXXXX XXXX XX
    XXXXXXXXXXXXX X
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXX XXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXXXXXX XXXXXXX
    X
    XX XXXXXX XXXXX XX XXXXXX XX
    XXXXXXX XXXXXXXXX X
      XXXXXX XXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXX XXXX
      XXXXXXXX XXXXX
      XXXXXXXXXXXX XXXXXXX
    X
    XXXXXXX XXXXXXXXX XX XXXXXXX XXXXXXXXX XXX X
      XXXXXXXXXXXXX XXXX
    X
    XX XXXX XXXXXX XXX XXX XXXXX XXXXXX XX XXXXXXX XXXXX XXXXXX XX
    XXXX X
      XXXXXXX XX
      XXXXXXXXXXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
    X
    XX XXXXXXX XXXXX XXX XX XXX XXXXXXX XX
    XXXXXXXXXXXXXXXXX X
      XXXXXXX X XXXXX
      XXXXXXXXXX XXXXXX
      XXXXXXXX X XXXXX
    X
    XXXXXXXXXXXXXXXXX XXX X
      XXXXXX XXXXX
      XXXXXXXXXXXXXX XXXX
    X
  XXXXXXXX
XXXXXXX
XXXXXX

  XXXX XXX XXXXXX XXX
  XXXX XXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXX X XXXXX XX XXXX XXX
      XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXX XXX XXXXX 
                XXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXX 
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXX
        XXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXX gettext(u'Quickdrop') XXXX
      XXXXXX
      XXXX XXXXX XXXXX XXXX XXXXXXX XXXXX XX XXXX XXX
      XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
        BB BBBBBBBBBBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                XXXX XXXXXX 
                     XXXXX gettext(u'Profile') X
                     XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXXXX
                
              XXXX
            XXXXX
          BBBB
            XXX XXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBXX
                XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Login') 
              XXXX
            XXXXX
          BBBBB
        BBBB
          XXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXX
              XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX gettext(u'Login') 
            XXXX
          XXXXX
        BBBBB
      XXXXX
    XXXXXX
  XXXXXX
  
  XXXX XXXXXXXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXX XXXXXX XXX XXXXX XXXXXXXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Quickdrop') XXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        BB BBBBBBBBBBBBBBBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XXXX XXXXXX 
                 XXXXX gettext(u'Profile') X
                 XXXXXXXXXXXXX XXXXX XXXXXXX XXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXX
            
          XXXXXX
        BBBB
          XXXX XXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX 
          XXXXXX
        BBBBB
      BBBB
        XX XXXXXXBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXX XXXXXXX
          XX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX gettext(u'Login') 
        XXXX
      BBBBB
    XXXXXX
    
    XXXX XXXXXXX XXXX XXX
    XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
        XXXX XXXX XXXX XXX
        XXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX  gettext(u'Menu') 
          XXXX
        XXXXX
        XXXX XXXX XXXX XXX
        XXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Cart') 
          XXXX
        XXXXX
        XXXX XXXXXXXXXXXX XXXX XXX
        XXX XXXXXXXXXXXXX
          XX XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
            XX XXXXXXXXX XXXXXXX XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Notifications') 
            XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
          XXXX
        XXXXX
        XXXX
        XXXX XXXXXX XXXXXXXX XXX
        XXX XXXXXXXXXXXXX
          XXXX XXXXXXXX XXXXXX XXXX XXX
          XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
            BBBBBBBBBB
            XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXX XXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXXXX XXXXXXX
                BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB
                BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
                BBB BBBBB BBBBBBBBB BB BBBBBBBBB
                  XXXXXXX XXXXXXXX BB BBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXX
                BBBBBB
              XXXXXXXXX
            XXXXXX
          XXXXXXX
        XXXXX
        XXXX XXXXXXXX XXXXXXX XXX
        XXX XXXXXXXXXXXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
            XX XXXXXXXXX XXXXXXXXXX XXXXXXXXXX  gettext(u'Customer Support') 
          XXXX
        XXXXX
        XXXX
        XXXX XXXXXXX X XXXXXX XXX XXXXXXXXXXXXXX XXX
        BB BBBBBBBBBBBBBBBBBBBBB
          XXX XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXX  gettext(u'Profile') 
            XXXX
          XXXXX
          BB BBBBBBBBBBBBB
            XXX XXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXX XXXXXXXX XXXXXXXXXX  gettext(u'Manage Orders') 
              XXXX
            XXXXX
          BBBBB
          XXX XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX  gettext(u'Logout') 
            XXXX
          XXXXX
        BBBBB
      XXXXX
    XXXXXX
  XXXXXX
  
  XXXX XXXXXX XXXXXXXX XXXX XXXX XXXXXX XXXXXX XXX
  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXX gettext(u'Banner') X XX
  XXXXXX
  
  XXXX XXXX XXXXXXX XXX
  XXXX XXXXXXXXXXXXXXXX XXXXXX
    BBBBB BBBBBBBBBBBBBBB BBBBBBB
  XXXXXX
  
  XXXX XXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXX XXXX  gettext(u'Quickdrop')  X XX XXXXXXXX XXXXXXXXXXXXXXXXXXX gettext(u'Privacy Policy') XXXXXXXX
    XXXXXX
  XXXXXXXXX
  
  XXXX XXXXXXXXX XX XXXXXXXXX XXXXXXX XXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  
  BBBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBB
  
  XXXXXXXX
    XX XXXXXXX XXXXXXXXXXXX XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX X
      XX XXXXXXXXXXXXXXX XX XXXXXXX X
        XX XXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
            XX XXXXXXXXXXX XXX XXXXXXXXXX X
              XXXXXXXXXXXXXXXXXXXXXXXXX
            X XXXX X
              XXXXXXX gettext(u'Notification permission was denied.') XXX
            X
          XXX
        X XXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXX
        X
      X XXXX X
        XXXXXXX gettext(u'This browser does not support desktop notifications.') XXX
      X
    X
  
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX X
      XXX XXXXXXXXXXXXXX gettext(u'Test Notification') XX X
        XXXXX X gettext(u'This is a test notification from Quickdrop.') XX
        XXXXX XBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX
      XXX
      XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX
    X
  XXXXXXXXX
XXXXXXX
XXXXXXX
