BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBB

BBBBB BBBBB gettext(u'Customer Support') BBBBBBBB BBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXX XXXXXXXXXXXXX gettext(u'Customer Support') XXXXX
  XXX gettext(u'Need Help? Contact us now.') XXXX

  XXX
    XXXXXXXX gettext(u'Call us at:') XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXX XXXXXXXXX
    XXXX
  XXXX

  XXX
    XXXXXXXX gettext(u'Email us at:') XXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
    XXXX
  XXXX

  XXX
    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Visit our website') 
    XXXX
  XXXX

  XXX
    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       gettext(u'Read our privacy policy') 
    XXXX
  XXXX

  XXXX XXXXXXXX XXXXXXXX XXXX XXX
  XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXX
    BBBBBBBBBB
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX gettext(u'Choose Language:') XXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXX XXXX XXXXXXXXX XX XXXXXX XXXXXXXXXX XXXX XX XXXXXXXXXXX XXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXX
       gettext(u'Switch') 
    XXXXXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB BBBBBBB
