BBBBBBB BBBBBBBBBBB
BBBB BBBBBBBBBBBBBB

BBBBB BBBBBXXXX XXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXX XXXXXXXXX
BB BBBB
  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXXXXXX
        XXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX
    XXXXXXX
      BBB BBBBBBBB BBBB BB BBBBBBBBBB
      XXXX
        XXXXXXXXX
        
        XXXX XXXXXXXX X X X XXXXXXX XXX
        XXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXX XXXXXXXXXXX
            XXXXXXXXXXXXX
            XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXX
          XXXXXX
        XXXXX
        
        XXXXXXXXXXXX
        XXXXXXXFFFFFFFFFFFFFFFFFFFXXXXX
        
        XXXX XXXXXX XXXXXX XXX
        XXXX
          XX 
            XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBBBBBBBBX 
            XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
          X
            XXXXXX
          XXXX
        XXXXX
      XXXXX
      BBBBBB
      XXXX
        XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX
  XXXXXXXX
  XX XXXXXXBBB BBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
BBBB
  XXXXXXX XXXX XX XXXXXXXXXX
BBBBB
BBBBBBBB
