BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXXXXXXXXXXXXXXX

XXXX XXXX XXXXXX XXXXXXX XXX
XXXXXXXXXX XXXX XXXXXXXXXX
XXXXXX XXXXXXXXXXXXXX
  XXXXXXX
    XXXX
      XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX
    XXXXX
  XXXXXXXX
  XXXXXXX
    BBB BBBBBBBB BBBB BB BBBBBBBBBB
    XXXX
      XXXXXXXXX
      XXXXXXXXX
      XXXXXXXXXXXX
    XXXXX
    BBBBBB
  XXXXXXXX
XXXXXXXX
XXXXXXXXXX XXXXXXXX

XXXX XXXXXXXX XXXX XXXXXXXXXX XXXXXX XXXXX XXX
XXXXX XXXXXXXXXXXXXX
  BBBBBBBBBB
  XXXX XXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
    XXXXXX 
      XXXXXXXXXXX 
      XXXXXXXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXXXXXX 
      XXXXXXXXXXXXXXXXXX XXXXX
    X
  XXXXXX
  XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
XXXXXXX
BBBBBBBB
