BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXXX
  
  XXXX XXXX XXXXXX XXXX XXX
  XXXXX XXXXXXXXXXXX XXXXXXXXXX XXX XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBXXXXXXXXBBBBBXXXXX X XXXXXXXXXXXXX
      XXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXX

  XXXX XXXXXX XXXXX XXX
  XXXXXX XXXXXXXXXXXXXX
    XXXXXXX
      XXXX
        XXXXXXXXX XXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXX
        XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXX
        XXXXXXXXXXXXXXXX
      XXXXX
    XXXXXXXX
    XXXXXXX
      BBB BBBBB BB BBBBBB
      XXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXX
          BB BBBBBBBBBBBBBBBBBB
            
          BBBB
            X
          BBBBB
        XXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXX XXXXX
        XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XX XXXXXXXX
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXX
            XXXXXXXX
          XXXX
          XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXX XXXXXXXX
            XXXXXX
          XXXX
        XXXXX
      XXXXX
      BBBBBB
    XXXXXXXX
  XXXXXXXX
XXXXXX
BBBBBBBB
