BBBBBBB BBBBBBBBBBB
BBBBB BBBBBXXXXX XXXXXXXXXXXXBBBBBBBB
BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXX XXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXX XXX XXX XXXX XXXXXXXXXX
      XXXX
      XXXX XXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXX
        XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXX
        BB BBBBBBBBBB
        XXXXXXXXXXXXXXXXXXXXXXXXX XXXX
        BBBBB
      XXXXXX
      XXXX XXXXXXXXXXXXX
        XXXXXXXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX
          BBB BBBB BB BBBBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          BBBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXXXXXXXX XXXXX XXXXX XXX XXXX XXXXXXXXXX
          XXXXXX
          BBBBBB
        XXXXXX
      XXXXXX
      XXXX XXXXXXXXXXXXXXXXX
        XX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBXXXXXX XX XXXXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
