BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXX XXXX XXXXX
BBBBBBBB BBBBB

BBBBB BBBBBBB
XXXXXXX
  XXXXXX XXXXXXXXXXX XXXXXX X
    XXXX X
      XXXXXXX XXXXXX
    X
  X
XXXXXXXX

XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXX XXXXXXXXXX
      XXXX XXXXXXXXXXX XXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX X XXXXXXXXXXXXX
          
          XX XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX 
            XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX
          
          XX XXXXXXXXXXXXXXXX XXXXXX
            XXXXXXXXXXXXX XXXXXXXXXXXXXXX 
            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXXX

          XXXX XXXXXXXXXX XXX XXXXXXXXX XXX
          XXXX XXXXXXXX XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXX XXXXX XXXXXXX XXXXXXXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBBB
XXXX XXXXXXX XXXX XXXX XXXXXX XXX XXX XXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXXXX
  XXX XXXX
  XXX XXXXXXX
  XXX XXXXXXXXXX X XXX

  XX XXXXXXX XXXXXXXXXX XXX XXXXXXX XXXXXXXXXXXXX
  XX XXXXXXXXXXXXXXX XX XXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX
      XX XXXXXXXXX XXXXX XX XXXXX XXXX XXXXXXXXXXXX XXXXX XXXXXXXXXX XX XXXXXXX
      XX XX XXXXXXXXXXX XXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
    XXX
  X

  XX XXXXXXXXXX XXX XXX XXXX X XXXXXXX XXXXXXXX XXXXXXXXX XXXX
  XXXXXXXX XXXXXXXXXXX X XX XXX X XX X
    XXXXX XXXXXX X X XXXX XXXX XXXX XXX XX
    XXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX XXXXXXX
      XXXXX XXX
    XXX
    XXXXXX X XXX XXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXX
      XXXX XXXX
    XXX
  X

  XX XXXXXX XXX XXXXXXXX XXXXXXXX XX XXX XXX
  XXXXXXXX XXXXXXXXXXXXXX XXXX X
    XXXXX XXXXXX X X XXXX XXXX XXXX XXX XX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXX
  X

  XX XXXX X XXXXXXXXXXXX XXXX XX XXXX XXX XX XXXXXXX XXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXXXXXXXXXXXXXX XX XXXX XXXXXXXXXXXX XXX XXXXXXXXX XXXXXXXXXXX
    XX XXXXX XXXXXXX XXXXX XXX XXXXXXXXXXXXX
    XXXXXXXXXXX XXXXX XXXXXX XXXXXXX XXX XXXXXXXXXXXXXXX

    XX XXXXX XXXXXXX XXXXXXXXXXXX XXXX X XXXXXX XXXX
    XX XXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX X
      XXX XXXXXXXXXXXXXXXXXXX XXXXXXXX X
        XXXXX XXXXX XXXXX XX XXXX XXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXX XXXX XXXX XX XXXXXXX
      XXX
    X XXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXX XX XXXXXXXXXXXXXXX
    X
  X

  XX XXXX XXX XXXXXX XXX XXXXX XXXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXX X
    XXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBBXX
      XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX
      XXXXXXXXXX XX X
        XX XXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXX
          XXXXXXX
        X
        XX XXXXXX XXXXXX XXXX XXX XXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXX

        XX XX XXXXXX XXXXXXXX XXXX XXXXXXXXXXXX
        XX XXXXXXXXXXXX XXX XXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX X XXXXXXXXXXXX
        X

        XX XXXXXX XXX XX XXXXXX XXXXXXXXXXX XXX XXXXXXXXX
        XX XXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        X
      XX
      XXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
  X

  XX XXXXXXXXXX XXX XXX
  XXXXXXXXXX

  XX XXXXX XXX XXXXXX XXXXX XXXXXX XXXXXXXXXXX XX XXXX
  XXXXXXXXXXXXXXXXXXX

  XX XXXX XXX XXXXX XXXXXXX XXXXX XX XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX
XXXXXXXXX
BBBBBBBB BBBBBBBBBBBBB
