# Generated by Django 5.1.7 on 2025-03-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_driver_lat_order_driver_lng_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
