# Generated by Django 5.1.7 on 2025-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_driver_image_order_driver_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver_phone',
        ),
    ]
